-- 1. Δημιουργία του τελικού πίνακα
CREATE TABLE IF NOT EXISTS docs (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    abstract text
);

--2 . Προσθήκη στηλών tsvector για αναζήτηση πλήρους κειμένου
ALTER TABLE docs
ADD COLUMN IF NOT EXISTS title_tsv tsvector,
ADD COLUMN IF NOT EXISTS abstract_tsv tsvector;

-- 3. Δημιουργία προσωρινού πίνακα για τη φόρτωση
CREATE TEMP TABLE temp_json (
    line_content TEXT
);

-- 4. Φόρτωση από το αρχείο (Το αρχείο πρέπει να βρίσκεται στο /tmp/data.json μέσα στο container)
COPY temp_json (line_content)
FROM '/tmp/data.json'
WITH (FORMAT csv, QUOTE e'\x01', DELIMITER e'\x02');

-- 5. Μεταφορά στον docs και εξαγωγή των πεδίων JSON
INSERT INTO docs (title, abstract)
SELECT 
    (line_content::jsonb) ->> 'title',
    (line_content::jsonb) ->> 'abstract'
FROM temp_json
WHERE line_content IS NOT NULL AND line_content != '';

-- 6. Δημιουργία των tsvectors
UPDATE docs SET 
    title_tsv = to_tsvector('english', COALESCE(title, '')),
    abstract_tsv = to_tsvector('english', COALESCE(abstract, ''));

-- 7. Δημιουργία των ευρετηρίων GIN
CREATE INDEX IF NOT EXISTS idx_title_tsv ON docs USING GIN(title_tsv);
CREATE INDEX IF NOT EXISTS idx_abstract_tsv ON docs USING GIN(abstract_tsv);